[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.5"

[features]
resolution = true
skip-lint = false

[programs.devnet]
conexple_protocol = "11111111111111111111111111111111"
conexple_network  = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
conexple_escrow   = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
conexple_oracle   = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"

[programs.localnet]
conexple_protocol = "11111111111111111111111111111111"
conexple_network  = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
conexple_escrow   = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
conexple_oracle   = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "keys/devnet-deployer.json"

[scripts]
test = "pnpm exec mocha -r ts-node/register --timeout 1000000 tests/full-flow.ts"

[test.validator]
url = "https://api.devnet.solana.com"
