[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.14"

[features]
resolution = true
skip-lint = false

[programs.devnet]
conexple_escrow = "9eTvjKrfbYy6JhFMJnuFo5ATCN6uS115J196bvPbmMXU"
conexple_network = "9nrHZqJcT3zLcK6eTu7ZLBBAU3Rr2eecnFYF413YePt9"
conexple_oracle = "9CQFV9oPYKWE4Yg4w8mwJxsdibPeZJrKoTqcp2iTi1qz"
conexple_protocol = "D1HVppRLhT6wmUxmaM4QABytmcBDEmKuuuMoa7HkKSbn"

[programs.localnet]
conexple_escrow = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
conexple_network = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
conexple_oracle = "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
conexple_protocol = "11111111111111111111111111111111"

[provider]
cluster = "devnet"
wallet = "keys/devnet-deployer.json"

[scripts]
test = "pnpm exec mocha -r ts-node/register --timeout 1000000 tests/full-flow.ts"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.devnet.solana.com"
ledger = '.anchor\test-ledger'
rpc_port = 8899
